spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ccl?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /var/sell.log
#  level:
#    com.imooc.LoggerTest: debug
#  path: /var/log